FROM node:alpine

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

COPY ./ ./

CMD [ "npm", "run", "start" ]

# docker build -f Dockerfile.dev .
# 이미지를 빌드할때 쓰일 도커 파일을 임의로 지정해준다.

# port를 3000으로 맵핑해줘야 함, it 옵션 무조건 줘야 함
# docker run -it -p 3000:3000 whiwoncho/docker-react-app
# docker run -it -p 3000:3000 -v /usr/src/app/node_modules -v $(pwd):/usr/src/app 
